### PR TITLE
converting over to use mocha for the test harness

### LINKED ISSUE #108: Do you mind if I update the tests to mocha?
Hey Folks, 

I was going to spend some time updating the testing system for this repo to mocha but I thought I should ask first ;) 

I was looking at the travis output for this PR https://github.com/quartzjer/ursa/pull/107 and I noticed that it didn't show a list of the tests that passed, instead it just says "All tests pass!" in the Travis output. If you have a look at one of my other modules and compare the Travis output https://travis-ci.org/Blooie/express-autoroute/jobs/74972233

Like i said, I would love to update the tests but I didn't want to just land a PR without asking first :wink:

### PR DESCRIPTION
**Pull request by mansona**
Fixes #108

### CODE REVIEW

**Comment by mansona** [comment]
Howdy 👋 

I know it's been a while since I offered to swap this repo over to using Mocha in #108 but I finally got around to doing it 🎉  You can see the output now lists all of the tests in Travis: https://travis-ci.org/quartzjer/ursa/jobs/202954687

One thing that I did notice through this implementation is that there was a function in the `native` test file that was never being called: `test_getPrivateKeyPemWithPassPhrase`. When I added it as a proper test it was creating a segfault so I marked it as a skipped test `it.skip()` which now shows up clearly in the test output. 

Just to be clear **this test was never running and I have just surfaced that information** 😂 

Now if you want to add tests or develop with this repo you can run `npm run test-watch` which will watch for changes to your files and re-run the tests. 

Let me know if you have any questions.

**Comment by mansona** [comment]
Also now that this is using Mocha it is trivial to enable code-coverage analysis via CodeClimate if that is something you were interested in. Please let me know if you would like me to help with that (you would need to sign up as the owner of the repo I think) 👍

**Comment by quartzjer** [comment]
@mansona I can no longer maintain this module and haven't found someone else to take it over yet, would you mind taking ownership?

**Comment by JoshKaufman** [comment]
@mansona I know its been a while since you worked on this 😅 but if you're still around how do you feel about this?

I'm going to compare/test it and merge so if you have anything to add 🗣

**Comment by mansona** [comment]
@JoshKaufman yes I still feel good about this PR, essentially it was just to make testing a little bit easier and more "modern"

Do you need me to bring it up to date or anything?

**Comment by JoshKaufman** [comment]
@mansona nah, I'm going to merge this and bump the npm versions separately as part of getting everything up to latest.

**Pull request merged**
